[package]
name = "tdn_did"
version = "0.1.0"
authors = ["CypherLink <contact@cypherlink.io>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
# tdn_types = "0.2"
tdn_types = { path = "../TDN/types" } # Dev
ed25519-dalek = "1.0"
sha3 = "0.9"
serde = { version = "1", features = ["derive"] }
